<template lang="pug">
  .relative-position.bg-white(style="padding-bottom:200px")
    svg(id="curveDownColor" xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="100" style="position:absolute; padding-top:0;  margin-top:0;fill: white; top:-100px;" viewBox="0 0 100 100" preserveAspectRatio="none")
      path(d="M0 100 C 60 10 90 50 100 100 Z")
    .row.justify-center.gutter-lg
      .col-12
        .row.justify-center
          .col
            h1.text-blue-5.text-center(style="text-shadow: 0px 1px 0px grey") BOID
            .row.justify-center
              img.boidtoken(src="~assets/NewBoidLogo.svg")
            // h4.text-blue-5.text-center.q-mt-xl(style="margin-bottom: 0px;") Our native token
        .row.justify-center.gutter-sm.q-ma-md
          .col-sm-12.col-md-10.col-lg-9.col-xl-9
            h5.text-center BOID will be the native token of the Boid EOS sidechain.
      .col-sm-12.col-md-6.col-lg-3.col-xl-2
        .relative-position.q-ma-md
          div(style="padding-top:15px; padding-left:20px")
            h6.tokeninfotext.text-grey-8 Initial Supply
            h4.tokendatatext {{totalSupply}} Billion
            h6.tokeninfotext.text-grey-8 Token Symbol
            h4.tokendatatext BOID
            h6.tokeninfotext.text-grey-8 EOS Snapshot date
            h4.tokendatatext June 1st
      .col-sm-12.col-md-10.col-lg-7.col-xl-5
        table.full-width.q-pa-lg
          tr
            td
              q-icon(name="important_devices" size="70px" color="blue-5")
            td(style="padding-top:5px; padding-left:20px")
              h6.bpHeading.text-grey-8 Unlock advanced features 
              h6.bpinfoText.text-black Users can stake (lock up) their BOIDs to gain access to advanced account functionality and platform bonuses.
          tr
            td
              q-icon(name="pan_tool" size="70px" color="blue-5")
            td(style="padding-top:35px; padding-left:20px")
              h6.bpHeading.text-grey-8 Have your say
              h6.bpinfoText.text-black Your BOIDs enable you to vote on proposals that have a direct impact on the future of the platform. 
          tr
            td
              q-icon(name="all_inclusive" size="70px" color="blue-5")
            td(style="padding-top:35px; padding-left:20px")
              h6.bpHeading.text-grey-8 Mineable  
              h6.bpinfoText.text-black Boid Power generated by the Boid app can be used to mine for BOIDs. BOIDS are minted as mining rewards at a dynamic rate based on the amount of "Boid Power" generated.
          tr
            td
              q-icon(name="domain" size="70px" color="blue-5")
            td(style="padding-top:35px; padding-left:20px")
              h6.bpHeading.text-grey-8 Supernodes 
              h6.bpinfoText.text-black Stake your BOIDs as part of a Boid supernode to provide important infrastructure support to the network. Each supernode is a associated with a specific team, and receives dividends based on team performance.
      .col-12
        .row.justify-center.gutter-lg
          .col-sm-12.col-md-10.col-lg-5.col-xl-3
            .row.justify-center
              .relative-position(style="max-width:380px;")
                distChart.cursor-pointer(:percentages="categoryPercentages" :activeItem="activeItem" @selected="getSelected")
                .absolute-center(style="z-index:1; pointer-events:none;")
                  img.boidtoken.cursor-pointer( style="pointer-events:none; user-select:none; width:300px;" @click="activeItem=null" src="~assets/NewBoidLogo.svg")
          .col-sm-12.col-md-10.col-lg-6.col-xl-3
            ul
              h5.cursor-pointer(style="max-width: 500px;" @click="activeItem=index" v-for="(item,index) in categories " :key="index" v-bind:class="{selected: activeItem===index, categoryList:activeItem != index}") 
                q-icon.inline(name="fiber_manual_record" :color="categoryColor[index]")
                | {{categoryPercentages[index]}}% {{item}}
                p(style="padding-left:38px;") {{tokenAmount(categoryPercentages[index])}} BOIDs
                h6.q-pa-lg.text-white(v-if="index === activeItem") {{categoryDescription[index]}}

</template>

<script>
import { openURL } from 'quasar'
import distChart from 'components/distributionchart.vue'

export default {
  // name: 'ComponentName',
  data () {
    return {
      totalSupply: 50,
      activeItem:null,
      categories:['Airdrop', 'Team','Development','Early Adopters','Advisors','Marketing'],
      categoryColor:['red-4','green-4','blue-4','orange-4','purple-3','yellow'],
      categoryDescription:[
        'Tokens are distributed fairly to EOS holders.',
        'The founding team tokens are vested over two years.',
        'These tokens are alloted for the growth of the development team and infrastructure.',
        'This includes incentives for participants duing the alpha and beta phases.',
        'Founding advisors receive tokens that vest over one year.',
        'This includes bounties and promotional events.'
        ],
      categoryPercentages:[10,25,25,10,5,25]
    }
  },
  methods:{
    openURL,
    getSelected(data){
      this.activeItem = data
    },
    tokenAmount(percentage){
      var supply = this.totalSupply * 1000000000
      console.log(supply)
      return (supply * (percentage * .01)).toLocaleString()
    }
  },
  watch:{
    'activeItem':()=>{
      console.log('activeItemChanged')
    }
  },
  components:{
    distChart
  }
}
</script>

<style lang="stylus">
  @import '~variables'
  .animate {
    transition-delay: .7s
    transition-duration: .25s
    transition-timing-function: ease-in
  }

  .slide-up {
    transform: translateY(-100px)
    opacity: 0
  }

  .slide-up.animate-active {
    transform: translateY(0)
    opacity: 1
  }

  .categoryList
    padding: 15px
    padding-top:25px
    padding-bottom:10px
    margin: 0px
    border-radius: 10px
  .categoryList:hover
    background-color:$grey-2
  .boidtoken
    // border-radius:100%
    filter: drop-shadow( 0px 5px 4px alpha(black,.3))
  .tokeninfotext
    font-size: 20px
  .tokendatatext
    margin-bottom 10px
    margin-top 10px
  .selected
    padding: 15px
    padding-top:25px
    padding-bottom:10px
    margin: 0px
    background-color $grey-8
    box-shadow 0px 4px 4px $grey-4
    border-radius: 10px
    color white
</style>
