<template lang="pug">
  .relative-position.bg-white(style="padding-bottom:200px")
    svg(id="curveDownColor" xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="100" style="position:absolute; padding-top:0;  margin-top:0;fill: white; top:-100px;" viewBox="0 0 100 100" preserveAspectRatio="none")
      path(d="M0 100 C 60 10 90 50 100 100 Z")
    .row.justify-center.gutter-lg
      .col-12
        .row.justify-center
          .col
            h1.text-blue-5.text-center(style="text-shadow: 0px 1px 0px grey") BOID
            .row.justify-center
              img.boidtoken.shadow-12(src="~assets/boidlogo1.png")
            // h4.text-blue-5.text-center.q-mt-xl(style="margin-bottom: 0px;") Our native token
        .row.justify-center.gutter-sm.q-ma-md
          .col-sm-12.col-md-10.col-lg-8.col-xl-7
            h5 BOID is the EOSIO token that will power the Boid blockchain.
            h6 The Token distribution is happening soon.
      .col-sm-12.col-md-6.col-lg-3.col-xl-2
        .relative-position.q-ma-md
          div(style="padding-top:15px; padding-left:20px")
            h6.tokeninfotext.text-grey-8 Initial Supply
            h4.tokendatatext 50 Billion
            h6.tokeninfotext.text-grey-8 Token Symbol
            h4.tokendatatext BOID
            h6.tokeninfotext.text-grey-8 EOS Snapshot date
            h4.tokendatatext June 1st
            h6.tokeninfotext.text-grey-8 Airdrop Ratio
            h4.tokendatatext 10:1
      .col-sm-12.col-md-10.col-lg-7.col-xl-4
        table.full-width.q-pa-lg
          tr
            td
              q-icon(name="important_devices" size="70px" color="blue-5")
            td(style="padding-top:5px; padding-left:20px")
              h6.bpHeading.text-grey-8 Unlock advanced features 
              h6.bpinfoText.text-black Users can stake (lock up) their BOIDs to gain access to advanced account functionality and platform bonuses.
          tr
            td
              q-icon(name="pan_tool" size="70px" color="blue-5")
            td(style="padding-top:35px; padding-left:20px")
              h6.bpHeading.text-grey-8 Have your say
              h6.bpinfoText.text-black Your BOIDs enable you to vote on proposals that have a direct impact on the future of the platform. 
          tr
            td
              q-icon(name="all_inclusive" size="70px" color="blue-5")
            td(style="padding-top:35px; padding-left:20px")
              h6.bpHeading.text-grey-8 Mineable  
              h6.bpinfoText.text-black Boid Power generated by the Boid app can be used to mine for BOIDs. BOIDS are minted as mining rewards at a dynamic rate based on the amount of computing power contributed towards the network.
          tr
            td
              q-icon(name="domain" size="70px" color="blue-5")
            td(style="padding-top:35px; padding-left:20px")
              h6.bpHeading.text-grey-8 Supernodes 
              h6.bpinfoText.text-black Stake your BOIDs as part of a Boid Supernode to provide important infrastructure support to the network. Each masternode is a associated with a specific team, and receives dividends based on team performance.
      .col-12
        .row.justify-center.gutter-lg
          .col-sm-12.col-md-10.col-lg-5.col-xl-3
            .row.justify-center
              .relative-position(style="max-width:400px;")
                distChart(:percentages="categoryPercentages" @hover="getHoverData")
                .absolute-center(style="z-index:1;")
                  img.boidtoken.shadow-12(  src="~assets/boidlogo1.png")
          .col-sm-12.col-md-10.col-lg-6.col-xl-4
            ul
              h5.categoryList.cursor-pointer( style="max-width: 500px;" @click="activeItem=index" v-for="(item,index) in categories " :key="index" v-bind:class="{selected: activeItem===index}") 
                q-icon(name="fiber_manual_record" :color="categoryColor[index]")
                |  {{categoryPercentages[index]}}% {{item}}
                h6.q-pa-lg.text-white(v-if="index === activeItem") {{categoryDescription[index]}}

      
              
            

</template>

<script>
import { openURL } from 'quasar'
import distChart from 'components/distributionchart.vue'

export default {
  // name: 'ComponentName',
  data () {
    return {
      activeItem:null,
      categories:['Airdrop', 'Team','Development','Early Adopters','Advisors','Marketing'],
      categoryColor:['red','green','blue','orange', 'yellow','purple'],
      categoryDescription:[
        'Distributed fairly to EOS token holders',
        'Founding team tokens are vested over two years',
        'Growing development team and infrastructure',
        'Bountys and rewards for users duing the Alpha and Beta phases.',
        'Founding advisors receive tokens that vest over one year',
        'This included bounties and promotional events'
        ],
      categoryPercentages:[10,25,25,10,5,25]
    }
  },
  methods:{
    openURL,
    getHoverData(data){
      if (data.length === 0) return
      this.activeItem = data[0]._index
    }
  },
  components:{
    distChart
  }
}
</script>

<style lang="stylus">
  @import '~variables'
  .animate {
    transition-delay: .7s
    transition-duration: .25s
    transition-timing-function: ease-in
  }

  .slide-up {
    transform: translateY(-100px)
    opacity: 0
  }

  .slide-up.animate-active {
    transform: translateY(0)
    opacity: 1
  }

  .categoryList
    padding: 10px
    margin: 0px
    border-radius: 10px
  .boidtoken
    border-radius:100%
  .tokeninfotext
    font-size: 20px
  .tokendatatext
    margin-bottom 10px
  .selected
    background-color $grey-8
    box-shadow 0px 4px 4px $grey-4
    color white
</style>
