<template lang="pug">
  .layout-padding(style="background-color:rgb(0, 112, 208); padding-bottom:300px;")
    .row.justify-center.q-mt-xl
      .col-xl-3.col-lg-5.col-md-6.col-sm-7.col-xs-8
        div(style="height: 230px;")
          h1.text-white.relative-position boid
            h1.text-white.absolute(style="top:80px") power
        h4.text-yellow-8(style="font-weight: 600; text-shadow: 1px 1px 1px yellow-6; white-space:nowrap;") Your gateway to the new economy
      .col-2.col-sm-1.col-xs-1
        .relative-position.justify-center
          img.boidPowerLogo(src="~assets/BoidPower.svg")
      .col-xs-3.lt-sm
    .row.justify-center
      .col-12-auto
        .row.justify-center.bpmasterrow
          .col-sm-12.col-md-5.col-lg-6.col-xl-6
            .row.justify-center
              img.bpicons(src="~assets/boidpower/generate.svg")
          .col-sm-12.col-md-7.col-lg-6.col-xl-6.relative-position(style="width:400px; height:300px;")
            .bpinfocard
              h6.bpHeading Devices generate Boid Power
              h6.bpinfoText The amount of Boid Power generated by a device is determined by it's hardware performance and how long the Boid application is running each day.
    .gt-sm.bpspacer
    .row.justify-center.q-mt-xl
      .col-12-auto
        .row.justify-center.reverse.bpmasterrow
          .col-sm-12.col-md-5.col-lg-6
            .row.justify-center
              img.bpicons(src="~assets/boidpower/competitions.svg")
          .col-sm-12.col-md-7.col-lg-6.relative-position(style="width:400px; height:300px;")
            .bpinfocard2
              h6.bpHeading Weekly competitions
              h6.bpinfoText Users compete in weekly challenges for money and prizes. Our global leaderboards are based on live Boid Power metrics.
    .gt-sm.bpspacer                
    .row.justify-center.q-mt-xl
      .col-12-auto
        .row.justify-center.bpmasterrow
          .col-sm-12.col-md-5.col-lg-6
            .row.justify-center
              img.bpicons(src="~assets/boidpower/passiveincome.svg")
          .col-sm-12.col-md-7.col-lg-6.relative-position(style="width:400px; height:300px;")
            .bpinfocard
              h6.bpHeading Passive Income
              h6.bpinfoText Your Boid Power can be used to mine for various cryptos. Get paid out daily however you like.
    .gt-sm.bpspacer              
    .row.justify-center.q-mt-xl
      .col-12-auto
        .row.reverse.justify-center.bpmasterrow
          .col-sm-12.col-md-5.col-lg-6
            .row.justify-center
              img.bpicons(src="~assets/boidpower/dogood.svg")
          .col-sm-12.col-md-7.col-lg-6.relative-position(style="width:400px; height:300px;")
            .bpinfocard2
              h6.bpHeading Do Good
              h6.bpinfoText Divert your Boid Power towards important non-profits in epic fundraising campaigns.

</template>

<script>
export default {
  // name: 'ComponentName',
  data () {
    return {}
  }
}
</script>

<style>
</style>
